Main app
Caren-Koroeny/BudgetApp pull request #1
Opened 2023-07-14 14:36 UTC by Caren-Koroeny

<h1>Hello :wave: Code Reviewer (s)</h1>

<h2> In this pull request I deployed my project that has the following features: </h2>

<h2> 1. Design </h2>

:mag: I followed t these [design guidelines](https://www.behance.net/gallery/19759151/Snapscan-iOs-design-and-branding?tracking_source=), including:
```
Colors.
Typography: font face, size and weight.
Layout: composition and space between elements.
```

Original design idea by [Gregoire Vella on Behance](https://www.behance.net/gregoirevella).

<h2>2. Interactions </h2> 

### Splash screen

- [ ] A simple page with the name of your app (yes, you need to choose one), and links to the sign up and log in pages.

### Sign up and log in pages

:eight_spoked_asterisk: The user should be able to register in the app with full name, email and password (all mandatory).
:eight_spoked_asterisk: The user can log into the app using email and password.
:eight_spoked_asterisk: If the user is not logged in, they can't access pages that require the user to be logged in (all the pages described below).

### Home page (categories page)

:eight_spoked_asterisk: When the user logs in, they are presented with the categories page.
:eight_spoked_asterisk: For each category, the user can see their name, icon and the total amount of all the transactions that belongs to that category.
:eight_spoked_asterisk: When the user clicks (or taps) on a category item, the application navigates to the transactions page for that category.
:eight_spoked_asterisk: There is a button "add a new category" at the bottom that brings the user to the page to create a new category.

### Transactions page

:eight_spoked_asterisk: For a given category, the list of transactions is presented, ordered by the most recent.
:eight_spoked_asterisk: At the top of the page the user could see the total amount for the category (sum of all of the amounts of the transactions in that category).
:eight_spoked_asterisk: There is a button "add a new transaction" at the bottom that brings the user to the page to create a new transaction.
:eight_spoked_asterisk: When the user clicks on the "Back" button (<), the user navigates to the home page.

### "Add a new category" page
:eight_spoked_asterisk: The user fills out a form to create a new category, indicating their name and icon (both mandatory).
:eight_spoked_asterisk: The user clicks (or taps) the "Save" button to create the new category, and is taken to the home page on success.
:eight_spoked_asterisk: When the user clicks on the "Back" button (<), the user navigates to the home page.

### "Add a new transaction" page

:eight_spoked_asterisk: The user fills out a form to create a new transaction with:
```
name (mandatory)
amount (mandatory)
categories (mandatory at least one)
```
:eight_spoked_asterisk: The user click (or taps) the "Save" button to create the new transaction, and is taken to the transactions page for that category.
:eight_spoked_asterisk:When the user clicks on the "Back" button (<), the user navigates to the transactions page for that category.
### Testing requirements
Create unit and integration tests for all the most important components of your RoR application.

### Technical requirements
:eight_spoked_asterisk: use Postgres as your database.
:eight_spoked_asterisk: use devise for authentication.
:eight_spoked_asterisk:  validate all user input to make sure that anyone with bad intentions cannot compromise your app.
:eight_spoked_asterisk: use a view template engine of your choice (.erb, .slim, .haml).
:eight_spoked_asterisk: project should be deployed and accessible online. [BudgetApp Live demo](https://budgetapp-kppa.onrender.com/)
:eight_spoked_asterisk: Your database schema should reflect the structure provided by microverse.

<h2>Knowledge :brain:  Gained :deciduous_tree: </h2>
<h3>I learnt how to: :bookmark: </h3>

Use ruby gems as software packages system.
Install Ruby on Rails framework.
Understand Rails RESTful design and router.
Use controllers to handle requests and render empty views.
Use params from browser request in a safe way.
Use preprocessed html file with embedded Ruby code.
Use layouts and templates for shared content.
Use database migration files to maintain database schema.
Use validations for models.
Secure app from n+1 problems.
Understand what ORM is.
Write SQL queries with ActiveRecord.
Set up associations between models.
Build a webapp that requires the user to log in.
Use devise gem for authentication.
Limit access to webapp resources based on authorization rules.
<h1> Screenshots </h1>

<h1>Happy Reviewing: :pray: </h1>

2023-07-14 16:34 UTC, Caren-Koroeny commented
Hello Code Reviewer, I see that the linter errors are not successful of them, am kindly asking for your help because on my end on the VS Code all `RUBOCOP` linters are all successful.

Below is a screenshot of it.

![Screenshot from 2023-07-14 19-32-55](https://github.com/Caren-Koroeny/BudgetApp/assets/55842414/f6f6da39-058c-4fef-8e5d-1019ab514097)

<h2> KINDLY ADVICE :pray: </h2>

2023-07-17 16:01 UTC, Nemwel-Boniface requested changes
## Hello @Caren-Koroeny :wave: 

### This is a manual review

# :recycle:  Request Changes :recycle: 

- [ ] You did super :raised_hands:  in your project. However, there are a few issue remaining to be addressed.
- [ ] Kindly have a look at the inline comments below.

![](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)

Cheers, and Happy coding! :rocket:

2023-07-17 16:01 UTC, Nemwel-Boniface commented on README.md
> +
You did super well in the video demo :clap:. However, there are these two issues that I found while checking your video:
     1. The introduction seems to be missing the aim/objective of your project. You only mentioned that this is a video for the RoR project that you did last week but did not explain what exactly your project is about and what you aim to achieve by completing the project.
     2. I was having a hard time hearing what you were saying. I believe t is an issue to do with the mic and you were not audible enough.

- [x] Kindly ensure that you retake the video presentation addressing the above-mentioned concerns.

2023-07-17 16:01 UTC, Nemwel-Boniface commented on README.md
> +
- [ ] It would be great to update your README instructing your visitors to ensure that they update the database.yml file with the required credentials to be able to setup the project database locally.

2023-07-17 16:01 UTC, Nemwel-Boniface commented on app/models/product.rb
> +  has_and_belongs_to_many :categories
- [ ] This seems to be a logical flaw here. A product is the one that owns a category and can also have many categories. This, therefore, means that a parent (product) cannot belong/ be formed from its own child (Category). The correct association here would be ```has_many```.

It would benefit you alot if you did a refresher of associations. [Here](https://guides.rubyonrails.org/association_basics.html#the-has-many-association) is the official docs showing the has_many association.

2023-07-17 17:06 UTC, Caren-Koroeny commented
Hello @Nemwel Boniface,

Thank you so much for the Review, I have done all the necessary changes as
requested on the Readme File and video repeat.
Below I have attached, the link to the new video that explains the
objective of the application, and also about the has_many association I
tried that but it's giving me a lot of errors, but I will check on what you
have suggested, once again thank you for the Review.

Kindly find the attached link to the video. Video Repeat
<https://drive.google.com/file/d/18xtif-Tu0S5O2leMIxpcQSwdJVhCk26u/view?usp=sharing>

Regards,
Caren Siya






On Mon, 17 Jul 2023 at 19:01, Nemwel Boniface ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> Hello @Caren-Koroeny <https://github.com/Caren-Koroeny> 👋 This is a
> manual review ♻️ Request Changes ♻️
>
>    - You did super 🙌 in your project. However, there are a few issue
>    remaining to be addressed.
>    - Kindly have a look at the inline comments below.
>
>
> <https://camo.githubusercontent.com/4f9601b422a77702aefe8e13485d2d5618cc0c30772eb2aa9f4129eac4757e06/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f4b7942657366386b4e5436733838534567622f67697068792e676966>
>
> Cheers, and Happy coding! 🚀
> ------------------------------
>
> In README.md
> <https://github.com/Caren-Koroeny/BudgetApp/pull/1#discussion_r1265557924>
> :
>
> > +## :movie_camera: Video documentation
> +
> +[video](https://drive.google.com/file/d/1Xl_bFObhxPLj3BjzapBIxR29iJxXPWar/view?usp=sharing)
> +
>
> You did super well in the video demo 👏. However, there are these two
> issues that I found while checking your video:
> 1. The introduction seems to be missing the aim/objective of your project.
> You only mentioned that this is a video for the RoR project that you did
> last week but did not explain what exactly your project is about and what
> you aim to achieve by completing the project.
> 2. I was having a hard time hearing what you were saying. I believe t is
> an issue to do with the mic and you were not audible enough.
>
>    - Kindly ensure that you retake the video presentation addressing the
>    above-mentioned concerns.
>
> ------------------------------
>
> In README.md
> <https://github.com/Caren-Koroeny/BudgetApp/pull/1#discussion_r1265561715>
> :
>
> > +### Setup
> +
> +Clone this repository to your desired folder:
> +
> +commands:
> +
> +```sh
> +  git clone ***@***.***:Caren-Koroeny/BudgetApp.git
> +```
> +
> +### Install
> +
> +Install this project with:
> +
> +command:
> +
> +```sh
> +  cd budget-app
> +  gem install
> +```
> +
> +### Usage
> +
> +To run the project, execute the following command:
> +
> +command:
> +
> +```sh
> +  rails s
> +```
> +
>
>
>    - It would be great to update your README instructing your visitors to
>    ensure that they update the database.yml file with the required credentials
>    to be able to setup the project database locally.
>
> ------------------------------
>
> In app/models/product.rb
> <https://github.com/Caren-Koroeny/BudgetApp/pull/1#discussion_r1265577884>
> :
>
> > @@ -0,0 +1,8 @@
> +# Documentation for the Product class.
> +class Product < ApplicationRecord
> +  belongs_to :author, class_name: 'User'
> +  has_and_belongs_to_many :categories
>
>
>    - This seems to be a logical flaw here. A product is the one that owns
>    a category and can also have many categories. This, therefore, means that a
>    parent (product) cannot belong/ be formed from its own child (Category).
>    The correct association here would be has_many.
>
> It would benefit you alot if you did a refresher of associations. Here
> <https://guides.rubyonrails.org/association_basics.html#the-has-many-association>
> is the official docs showing the has_many association.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Caren-Koroeny/BudgetApp/pull/1#pullrequestreview-1533103805>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANKBM3W5ZAQMI7G7HELHJQTXQVOXFANCNFSM6AAAAAA2KNJHRQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-07-17 21:24 UTC, Nemwel-Boniface approved these changes
## Hello @Caren-Koroeny :wave: 

### This is a manual review

# :heavy_check_mark:  Approved :heavy_check_mark:

- [ ] You did well making the requested changes :clap: 
- [ ] You have an awesome project here! :fire: 

![](https://media.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif)

Cheers, and Happy coding! :rocket:

2023-07-17 21:24 UTC, Nemwel-Boniface commented on app/models/product.rb
> +  has_and_belongs_to_many :categories
- [ ] I had to re-read the docs and I found that both will actually work. However, I also found that the ```has_and_belongs_to_many``` bests fits here based on the fact that there will be a many to many relationships being established. This is also captured in the provided ERD when I rechecked. I, therefore, agree with you that the ```has_and_belongs_to_many``` is the best association for this scenario.

![image](https://github.com/Caren-Koroeny/BudgetApp/assets/86318284/92d958d9-0bb0-4cc8-a6f4-daf006aebe70)

2023-07-17 23:03 UTC, merged